app/employee/urls.py
from django.urls import path, include
from app.employee import views

app_name = "employee"

urlpatterns = [
    path('employee', views.EmployeeListView.as_view(), name="list"),
    path('create', views.EmployeeCreateView.as_view(), name="create"),
    path('edit/<str:pk>', views.EmployeeUpdate.as_view(), name="update"),
    path('delete/<str:pk>', views.EmployeeDelete.as_view(), name='delete'),


    path('job', views.JobListView.as_view(), name="list-job"),
    path('job-create', views.JobCreateView.as_view(), name="create-job"),
    path('job-delete/<int:pk>', views.JobDeleteView.as_view(), name='delete-job'),
    path('job-edit/<int:pk>', views.JobEditView.as_view(), name="edit-job"),
    
]

app/payroll/urls.py
from django.urls import path
from app.payroll import views

app_name = "payroll"

urlpatterns = [
    # path('', views.PayrollView.as_view(), name='list'),
    path('form/<str:pk>', views.PayrollView.as_view(), name="form"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from app.employee.views import Index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view()),
    path('employee/', include('app.employee.urls', namespace='employee-url')),
    path('payroll/', include('app.payroll.urls', namespace='payroll-url')),
]

app/api/models.py
from django.db import models

# Create your models here.

app/employee/models.py
from django.db import models
from django.utils import timezone


class Kota(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class JobPosition(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    salary = models.DecimalField(max_digits=8, decimal_places=2)
    detail = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.name} -> {self.salary}'
    

class Employee(models.Model):

    nip = models.CharField(max_length=11,
            primary_key=True, null=False,
            blank=False, help_text="Nomor Induk Pegawai")

    name = models.CharField(max_length=40, blank=False,
            null=False, help_text="Nama Pegawai")

    # JABATAN = (
    #     ('Staff', 'Staff'),('Non Staff', 'Non Staff')
    # )

    job_position = models.ForeignKey(JobPosition, on_delete=models.SET_NULL, blank=True, null=True)

    GENDER = (('Male', 'Male'),('Female','Female'))

    gender = models.CharField(max_length=10, choices=GENDER,
        blank=False, null=True, help_text="Pilih Jenis Kelamin")

    date_of_birth = models.DateField(auto_now=False, null = True, default = '2019-11-06')
    place_of_birth = models.CharField(max_length=255, blank=False, null=True)
    address = models.TextField(max_length=50, blank=True,
        null=True, help_text="Masukkan Alamat Pegawai")    

    kota = models.ForeignKey(Kota, on_delete=models.CASCADE, blank=True, null=True)

    created = models.DateTimeField(auto_now=False, auto_now_add=True, blank=True, null=True) 
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, blank=True, null=True)


    def __str__(self):
        return self.name

app/payroll/models.py
from django.db import models
from app.employee.models import Employee


class Payroll(models.Model):

    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, blank=True, null=True)
    allowance = models.DecimalField(max_digits=10, decimal_places=2)
    overtime = models.DecimalField(max_digits=10, decimal_places=2)
    add_earnings = models.DecimalField(max_digits=10, decimal_places=2)
    thp = models.DecimalField(max_digits=10, decimal_places=2)

app/employee/forms.py
from django import forms
from app.employee.models import Employee


class DateInput(forms.DateInput):
    input_type = 'date'


class EmployeeForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=DateInput)

    class Meta:
        model = Employee
        fields = '__all__'

    
    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

app/payroll/forms.py
from django import forms
from app.payroll.models import Payroll


class PayRollForm(forms.ModelForm):
    class Meta:
        model = Payroll
        fields = '__all__'

app/api/views.py
from django.shortcuts import render

# Create your views here.

app/employee/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views import generic 
from django.urls import reverse_lazy
from django.forms.models import model_to_dict
from app.employee import forms, models


class FormMixin(object):
    form_class = forms.EmployeeForm
    model = models.Employee
    success_url = reverse_lazy('employee-url:list')


# class DeleteMixin:
    # def get_url(self):
        # object_meta = self.object._meta
        # names.append("%s/%s%s.html" % (
        #     object_meta.app_label,
        #     object_meta.model_name,
        #     self.template_name_suffix
        # ))
        # if self.url:
        #     return self.url
        # return None

    # def post(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     self.object.delete()

    #     return HttpResponseRedirect(reverse_lazy(self.get_url()))    


class Index(generic.TemplateView):
    template_name = "home.html"
 

class EmployeeCreateView(FormMixin, generic.CreateView):
    pass


class EmployeeListView(generic.ListView):
    queryset = models.Employee.objects.all().order_by('-name')


class EmployeeUpdate(FormMixin, generic.UpdateView):
    pass


class EmployeeDelete(generic.DeleteView):
    success_url = reverse_lazy("employee-url:list")
    model = models.Employee


class JobListView(generic.View):
    template_name = "employee/jobposition_list.html"

    def get(self, request):
        data = {
            "range": range(0,10),
            "job": models.JobPosition.objects.all()
        }
        return render(request, self.template_name, data)
        

class JobCreateView(generic.View):
    template_name = "employee/jobposition_form.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = request.POST
        obj = models.JobPosition()
        obj.name = form.get('name')
        obj.salary = form.get('salary')
        obj.detail = form.get('detail')
        obj.save()

        return redirect('employee-url:list-job')


class JobEditView(generic.View):
    template_name = "employee/jobposition_edit.html"

    def get(self, request, pk):
        obj = get_object_or_404(models.JobPosition, pk=pk)
        data = {
            "obj": obj
        }
        return render(request, self.template_name, data)

    def post(self, request, pk):
        form = request.POST
        obj = get_object_or_404(models.JobPosition, pk=pk)
        obj.name = form.get('name')
        obj.salary = form.get('salary')
        obj.detail = form.get('detail')
        obj.save(force_update=True)

        return redirect('employee-url:list-job')


class JobDeleteView(generic.DeleteView):
    model = models.JobPosition
    success_url = reverse_lazy("employee-url:list-job")

app/payroll/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .forms import PayRollForm
from app.employee.models import Employee


class PayrollView(generic.View):
    template_name = "payroll/form.html"

    def get(self, request, pk):
        employee = get_object_or_404(Employee, pk=pk)
        form = PayRollForm()
        data = {
            "form": form,
            "employee": employee
        }
        return render(request, self.template_name, data)

app/employee/templates/employee/employee_confirm_delete.html
{% extends "index.html" %}

{% block container %}
    <form method="POST">
        <p>Yakin menghapus {{ object }}?</p>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock container %}

app/employee/templates/employee/employee_form.html
{% extends "index.html" %}

{% block container %}  
    <h5>Form data</h5>
    <table class="table">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td colspan="3">
                    <input class="btn btn-success btn-block" type="submit" value="SIMPAN">
                </td>
            </tr>
        </form>
    </table>
{% endblock container %}

app/employee/templates/employee/employee_list.html
{% extends "index.html" %}

{% block container %}
    <a class="btn btn-primary btn-sm" href="{% url 'employee-url:create' %}">Tambah</a><br /><br />
    <h5><u>List Employee</u></h5>

    <table class="table table-striped table-hover">
        <tr>
            <th>No.</th>
            <th>NIP</th>
            <th>Nama</th>
            <th>Jabatan</th>
            <th>Gender</th>
            <th>Tempat/Tanggal Lahir</th>
            <th>Kota</th>
            <th>Alamat</th>
            <th>Proses</th>
        </tr>
        {% for obj in object_list %}          
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{obj.nip}}</td>
                <td>{{obj.name}}</td>
                <td>{{obj.job_position.name}}</td>
                <td>{{obj.gender}}</td>
                <td>
                    {% if obj.place_of_birth %}
                        {{obj.place_of_birth}}
                    {% else %}
                        -
                    {% endif %}
                    ,{{obj.date_of_birth}}
                </td>
                <td>{{ obj.kota.name }}</td>
                <td>
                    {% if obj.address %}
                        {{obj.address}}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'employee-url:update' pk=obj.pk %}">Edit</a>
                    | 
                    <a href="{% url 'employee-url:delete' pk=obj.pk %}">Delete</a>
                    |
                    <a onclick="return confirm('Pay?')" href="{% url 'payroll-url:form' pk=obj.pk %}">Pay</a>

                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock container %}

app/employee/templates/employee/jobposition_confirm_delete.html
{% extends "index.html" %}

{% block container %}
    <form method="POST">
        <p>Yakin menghapus {{ object }}?</p>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock container %}

app/employee/templates/employee/jobposition_edit.html
{% extends "index.html" %}

{% block container %}
    <form action="{% url 'employee-url:edit-job' pk=obj.pk %}" method="POST">
        {% csrf_token %}
        Nama<br />
        <input class="form-control" value="{{ obj.name }}"
            type="text" name="name"><br />

        Salary<br />
        <input class="form-control" value="{{ obj.salary }}"
            type="number" name="salary"><br />

        Keterangan<br />
        <textarea class="form-control" name="detail"
            cols="30" rows="10">{{ obj.detail }}</textarea><br />

        <input class="btn btn-danger btn-block" type="submit" value="SIMPAN">
    </form>
{% endblock container %}

app/employee/templates/employee/jobposition_form.html
{% extends "index.html" %}

{% block container %}
    <form action="{% url 'employee-url:create-job' %}" method="POST">
        {% csrf_token %}
        Nama<br />
        <input class="form-control" type="text" name="name"><br />

        Salary<br />
        <input class="form-control" type="number" name="salary"><br />

        Keterangan<br />
        <textarea class="form-control" name="detail" cols="30" rows="10"></textarea><br />

        <input class="btn btn-danger btn-block" type="submit" value="SIMPAN">
    </form>
{% endblock container %}

app/employee/templates/employee/jobposition_list.html
{% extends "index.html" %}

{% block container %}
    <h6>List Job Position</h6>
    <a class="btn btn-dark btn-sm" href="{% url 'employee-url:create-job' %}">Tambah Data</a><br /><br />
    <table class="table table-striped table-hover">
        <tr>
            <th>No.</th>
            <th>Nama</th>
            <th>Salary</th>
            <th>Proses</th>
        </tr>

        {% for data in job %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ data.name }}</td>
                <td>{{ data.salary }}</td>

                <td>
                    <a href="{% url 'employee-url:edit-job' pk=data.pk %}">Edit</a> |
                    <a href="{% url 'employee-url:delete-job' pk=data.pk %}">Delete</a> |
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock container %}

app/payroll/templates/payroll/form.html
{% extends "index.html" %}

{% block container %}
    <form action="{% url 'payroll-url:form' pk=employee.pk %}" method="post">
        <div class="form-row">
          <div class="form-group col-md-4">
            <label>Nama</label>
            <input class="form-control disabled" value="{{ employee.name }}" disabled />
          </div>
          <div class="form-group col-md-4">
            <label>NIP</label>
            <input class="form-control disabled" value="{{ employee.nip }}" disabled />
          </div>
          <div class="form-group col-md-4">
                <label>Job Position</label>
                <input class="form-control disabled" value="{{ employee.job_position.name }}" disabled />
            </div>
        </div>
        <div class="form-group">
          <label>Alamat</label>
          <input class="form-control disabled" value="{{ employee.address }}" disabled />
        </div>
        
        <div class="form-row">
          <div class="form-group col-md-3">
            <label for="inputCity">Allowance</label>
            <input name="allowance" type="text" class="form-control">
          </div>
          <div class="form-group col-md-3">
            <label>Overtime</label>
            <input name="overtime" type="text" class="form-control"/>
          </div>
          <div class="form-group col-md-3">
            <label>Add Earnings</label>
            <input name="add_earnings" type="text" class="form-control" />
          </div>
          <div class="form-group col-md-3">
            <label>THP</label>
            <input name="thp" type="text" class="form-control" />
        </div>
        </div>
        <button type="submit" class="btn btn-dark btn-block">Submit Pay</button>
    </form>
{% endblock container %}

employee/templates/employee/form_employee.html
{% extends "index.html" %}

{% block container %}  
    <h5>Form tambah data</h5>
    <table class="table">
        <form action="/employee/form/" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td>
                    <input class="btn btn-success" type="submit" value="SIMPAN">
                </td>
            </tr>
        </form>
    </table>
{% endblock container %}

employee/templates/employee/list_employee.html
{% extends "index.html" %}

{% block container %}
    <a class="btn btn-primary btn-sm" href="/employee/form/">Tambah</a><br /><br />
    <h5><u>List Employee</u></h5>

    <table class="table table-striped table-hover">
        <tr>
            <th>No.</th>
            <th>NIP</th>
            <th>Nama</th>
            <th>Jabatan</th>
            <th>Gender</th>
            <th>Tanggal Lahir</th>
            <th>Alamat</th>
            <th>Proses</th>
        </tr>
        {% for obj in object_list %}          
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{obj.nip}}</td>
                <td>{{obj.name}}</td>
                <td>{{obj.job_Position}}</td>
                <td>{{obj.gender}}</td>
                <td>{{obj.date_of_birth}}</td>
                <td>{{obj.addres}}</td>
                <td>
                    <a href ="{% url 'employee-url:edit' nip=obj.nip %}">Edit</a> | Hapus
                </td>
            </tr>
        {% endfor %}
    </table>

    <!-- {% for obj in object_list %}
        <p>{{obj.name}}</p>
    {% endfor %} -->
{% endblock container %}

templates/home.html
{% extends "index.html" %}

{% block container %}
    Selamat datang user
{% endblock container %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Payroll</title>
</head>

<body>
    <div class="container-fluid">

        <div class="row header">
            <div class="col-md-12">
                <h2>Aplikasi Payroll PT. Rindri</h>
            </div>
        </div>

        <div class="row tengah">
            <div class="content col-md-9">
                {% block container %}

                {% endblock container %}
            </div>
            <div class="sidebar col-md-3">
                <div class="list-group">
                    <a class="list-group-item list-group-item-action active" href="/">Home</a>
                    <a class="list-group-item list-group-item-action" href="{% url 'employee-url:list' %}">Employee</a>
                    <a class="list-group-item list-group-item-action" href="{% url 'employee-url:list-job' %}">Job
                        Position</a>
                </div>
            </div>
        </div>
        <div class="row footer">
            <div class="col-md-12">
                <p>Copyright &copy; Rindri</p>
            </div>
        </div>
    </div>
</body>

</html>

templates/list_employee.html
{% extends "index.html" %}

{% block container %}
    <a class="btn btn-primary btn-sm" href="/employee/form/">Tambah</a><br /><br />
    <h5><u>List Employee</u></h5>

    <table class="table table-striped table-hover">
        <tr>
            <th>No.</th>
            <th>NIP</th>
            <th>Nama</th>
            <th>Jabatan</th>
            <th>Gender</th>
            <th>Tanggal Lahir</th>
            <th>Alamat</th>
            <th>Proses</th>
        </tr>
        {% for obj in object_list %}          
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{obj.nip}}</td>
                <td>{{obj.name}}</td>
                <td>{{obj.job_Position}}</td>
                <td>{{obj.gender}}</td>
                <td>{{obj.date_of_birth}}</td>
                <td>{{obj.addres}}</td>
                <td>
                    Edit | Hapus
                </td>
            </tr>
        {% endfor %}
    </table>

    <!-- {% for obj in object_list %}
        <p>{{obj.name}}</p>
    {% endfor %} -->
{% endblock container %}